package onchain

const (
    ColAccountID          = "account_id"
    ColAmount             = "amount"
    ColBlockNumber        = "block_number"
    ColToken              = "token"
    ColChain              = "chain"
    ColConfirmations      = "confirmations"
    ColConfirmedAt        = "confirmed_at"
    ColCreatedAt          = "created_at"
    ColEventIndex         = "event_index"
    ColExpiresAt          = "expires_at"
    ColFromAddress        = "from_address"
    ColID                 = "id"
    ColIntentID           = "intent_id"
    ColMemo               = "memo"
    ColMetadata           = "metadata"
    ColNetwork            = "network"
    ColOwnerRef           = "owner_ref"
    ColRecipientType      = "recipient_type"
    ColRecipientAddress   = "recipient_address"
    ColStatus             = "status"
    ColToAddress          = "to_address"
    ColTxHash             = "tx_hash"
    ColUpdatedAt          = "updated_at"
    ColWebhookEndpointID  = "webhook_endpoint_id"
)
