package onchain

const (
    ColAccountID           = "account_id"
    ColAddress             = "address"
    ColAmount              = "amount"
    ColBlockNumber         = "block_number"
    ColChain               = "chain"
    ColChainFamily         = "chain_family"
    ColCreatedAt           = "created_at"
    ColCustomerRef         = "customer_ref"
    ColEncryptedPrivateKey = "encrypted_private_key"
    ColToken               = "token"
    ColConfirmations       = "confirmations"
    ColConfirmedAt         = "confirmed_at"
    ColEventIndex          = "event_index"
    ColExpiresAt           = "expires_at"
    ColFromAddress         = "from_address"
    ColID                  = "id"
    ColIntentID            = "intent_id"
    ColKind                = "kind"
    ColMemo                = "memo"
    ColMetadata            = "metadata"
    ColNetwork             = "network"
    ColOwnerRef            = "owner_ref"
    ColRecipientID         = "recipient_id"
    ColRecipientKind       = "recipient_kind"
    ColRecipientAddress    = "recipient_address"
    ColSecretKeyVersion    = "secret_key_version"
    ColSecretProviderKind  = "secret_provider_kind"
    ColStatus              = "status"
    ColToAddress           = "to_address"
    ColTxHash              = "tx_hash"
    ColUpdatedAt           = "updated_at"
    ColWebhookEndpointID   = "webhook_endpoint_id"
)
